{% set name = "langchain-azure-dynamic-sessions" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/langchain_azure_dynamic_sessions-{{ version }}.tar.gz
  sha256: 315ff79635dbc8c220a39078802d878714bb5a1a1e85d4e46a71530507c7195f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8.1,<4.0
    - langchain-core >=0.1.52,<0.3
    - azure-identity >=1.16.0,<2.0.0
    - requests >=2.31.0,<3.0.0

test:
  imports:
    - langchain_azure_dynamic_sessions
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/langchain-ai/langchain
  summary: An integration package connecting Azure Container Apps dynamic sessions and LangChain
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
